language: r
dist: trusty
sudo: required
warnings_are_errors: true

# cache: packages   # to rebuild cache see tweet thread ending here https://twitter.com/jimhester_/status/1115718589804421121

cache:
  - ccache # See: https://pjs-web.de/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/

addons:
  apt:
    packages:
     - ccache

before_install:
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr # used for code coverage reports in github pull requests

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change