language: r
dist: trusty
sudo: required
warnings_are_errors: true

cache: packages   # to rebuild cache see tweet thread ending here https://twitter.com/jimhester_/status/1115718589804421121

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr # used for code coverage reports in github pull requests

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change