language: r
dist: trusty
sudo: required
cache: packages   # to rebuild cache see tweet thread ending here https://twitter.com/jimhester_/status/1115718589804421121
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr # used for code coverage reports in github pull requests

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change