# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps:
    $ErrorActionPreference = "Stop"
    Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
    Import-Module '..\appveyor-tool.ps1'
install:
  - ps: Bootstrap
  - cmd: Rscript -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
  - cmd: Rscript -e "getOption('repos')"
  # The following line is different from the template:
  # we need to install tic from our local source!
  - cmd: Rscript -e "install.packages('remotes')"
  - cmd: Rscript -e "remotes::install_local(getwd(), force = TRUE)"

skip_branch_with_pr: true

environment:
  global:
    USE_RTOOLS: true

  matrix:

  - R_VERSION: release  # the single Windows.zip binary (both 32bit/64bit) that users following dev version of installation instructions should click

  - R_VERSION: devel

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits