// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// copulaCorrection_LL_rcpp
double copulaCorrection_LL_rcpp(const NumericVector& params, const NumericVector& vec_y, const NumericMatrix& m_data_exo_endo, const NumericVector& vec_data_endo_pstar);
RcppExport SEXP _REndo_copulaCorrection_LL_rcpp(SEXP paramsSEXP, SEXP vec_ySEXP, SEXP m_data_exo_endoSEXP, SEXP vec_data_endo_pstarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type vec_y(vec_ySEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type m_data_exo_endo(m_data_exo_endoSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type vec_data_endo_pstar(vec_data_endo_pstarSEXP);
    rcpp_result_gen = Rcpp::wrap(copulaCorrection_LL_rcpp(params, vec_y, m_data_exo_endo, vec_data_endo_pstar));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_REndo_copulaCorrection_LL_rcpp", (DL_FUNC) &_REndo_copulaCorrection_LL_rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_REndo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
