#' @title Internal: Single 2sCOPE Model Fit
#' @description
#' Internal function that performs a single 2sCOPE model fit. This function contains the core
#' computation logic and is called by both the main tscope function and during bootstrapping.
#' It should not be called directly by users.
#'
#' @param formula A formula or Formula object specifying the model, with two parts separated by '|'.
#' @param data A data.frame containing all variables referenced in the formula.
#' @param verbose Logical indicating whether to print progress messages.
#'
#' @return A list containing the model results for a single fit.
#'
#' @importFrom Formula as.Formula
#' @importFrom stats lm model.frame model.matrix model.response sd cor coef residuals
#' 
#' @keywords internal
tscope_fit <- function(formula, data, verbose = TRUE) {
  cl <- match.call()
  
  # Convert formula and build model frame ---------------
  F.formula <- as.Formula(formula)
  
  # Create model frame first to handle complex formulas properly
  mf <- model.frame(F.formula, data = data)
  
  # Extract all regressors from the first part (including intercept)
  x <- as.matrix(model.matrix(F.formula, data = mf, rhs = 1))
  
  # Extract dependent variable
  response_name <- names(mf)[1]
  y <- model.response(mf)
  
  # Extract endogenous regressors from the SECOND RHS part of the formula (remove intercept)
  endox <- as.matrix(model.matrix(F.formula, data = mf, rhs = 2))
  endox <- endox[, colnames(endox) != "(Intercept)", drop = FALSE]
  nendox <- ncol(endox)
  
  # Extract exogenous regressors (w)
  w <- x[, -which(colnames(x) %in% c("(Intercept)", colnames(endox))), drop = FALSE]
  nw <- ncol(w)

  if (verbose) {
    if (nendox > 0) {
      message(paste(strwrap(paste0("Found ", nendox, " endogenous regressor(s): ",
                                   paste(colnames(endox), collapse = ", "))), collapse = "\n"))
    } else {
      message("No endogenous regressors found.")
    }
    if (nw > 0) {
      message(paste(strwrap(paste0("Found ", nw, " exogenous regressor(s): ",
                                   paste(colnames(w), collapse = ", "))), collapse = "\n"))
    } else {
      message("No exogenous regressors found.")
    }
  }

  # Calculate endoxstar using helper function and ensure syntactically valid names
  endoxstar <- ecdf_transform_regressors(endox)
  gen_names <- make.names(paste0(colnames(endox), ".Star"), unique = TRUE)
  colnames(endoxstar) <- gen_names

  if (nw == 0) {
    # No exogenous regressors: direct fit
    if (verbose) {
      message(paste(strwrap("Direct fit: Using copula-transformed endogenous regressors without residualization."),
                    collapse = "\n"))
    }
    stage1_resid <- NULL
    
    combined_data <- data
    
    # Add the (potentially synthetic) main-model regressors that do not already
    # exist in the user data. These include interaction terms such as "p:w" or
    # function calls like "I(w^2)" which are generated by model.matrix().
    main_vars <- setdiff(colnames(x), "(Intercept)")  # Exclude intercept if present
    
    missing_main_vars <- setdiff(main_vars, names(combined_data))
    if (length(missing_main_vars) > 0) {
      for (v in missing_main_vars) {
        if (v %in% colnames(mf)) {
          combined_data[[v]] <- mf[[v]]
        } else if (v %in% colnames(x)) {
          combined_data[[v]] <- x[, v]
        }
      }
    }
    
    # Bind the generated copula transformed endogenous regressors
    generated_vars <- colnames(endoxstar)
    combined_data[generated_vars] <- endoxstar
    
    # Construct formula respecting original intercept specification
    intercept_present <- "(Intercept)" %in% colnames(x)
    intercept_prefix <- if (intercept_present) "" else "0 + "
    formula_str <- paste(response_name, "~", intercept_prefix, paste(c(main_vars, generated_vars), collapse = " + "))
    res <- lm(as.formula(formula_str), data = combined_data)
    if (verbose) {
      message(paste(strwrap(paste0("Fitting final model: ",
                                   formula_str)), collapse = "\n"))
    }
    
  } else {
    # With exogenous regressors: two-stage fit
    if (verbose) {
      message(paste(strwrap("STAGE 1: Residualizing transformed endogenous regressors on transformed exogenous regressors."),
                    collapse = "\n"))
    }
    # Calculate wstar using helper function
    wstar <- ecdf_transform_regressors(w)
    colnames(wstar) <- colnames(w)
  
    stage1_resid <- qr.resid(qr(cbind(1, wstar)), endoxstar)
    if (is.null(dim(stage1_resid))) {
      # Ensure the result is always a matrix for consistent downstream handling
      stage1_resid <- matrix(stage1_resid, ncol = 1)
    }
    # Follow package-wide convention to use suffixes like `.resid`
    colnames(stage1_resid) <- make.names(paste0(colnames(endox), ".resid"), unique = TRUE)
    
    # Improved data handling, retain original variables required for any inline
    # transformations and add the residualised endogenous regressors
    combined_data <- data
    
    # Add (synthetic) main model regressors that are not present in the original data
    main_vars <- setdiff(colnames(x), "(Intercept)")  # Exclude intercept if present
    missing_main_vars <- setdiff(main_vars, names(combined_data))
    if (length(missing_main_vars) > 0) {
      for (v in missing_main_vars) {
        if (v %in% colnames(mf)) {
          combined_data[[v]] <- mf[[v]]
        } else if (v %in% colnames(x)) {
          combined_data[[v]] <- x[, v]
        }
      }
    }
    
    # Add Stage-1 residual variables
    resid_vars <- colnames(stage1_resid)
    combined_data[resid_vars] <- stage1_resid
    
    # Construct formula respecting original intercept specification
    intercept_present <- "(Intercept)" %in% colnames(x)
    intercept_prefix <- if (intercept_present) "" else "0 + "
    formula_str <- paste(response_name, "~", intercept_prefix, paste(c(main_vars, resid_vars), collapse = " + "))
    res <- lm(as.formula(formula_str), data = combined_data)
    if (verbose) {
      message(paste(strwrap(paste0("STAGE 2: Final model specification: ",
                                   formula_str)), collapse = "\n"))
    }
  }

  # Extract main model coefficients (only those corresponding to x matrix)
  coef_x <- coef(res)[1:ncol(x)]
  
  # Calculate fitted values and residuals from the main model (not from final res object)
  fitted.values <- c(x %*% coef_x)
  names(fitted.values) <- rownames(mf)
  resid2 <- y - fitted.values
  names(resid2) <- rownames(mf)
  
  # Compute correlations between transformed endogenous regressors and main model residuals for diagnostics
  corr_endostar_resid <- apply(endoxstar, 2, function(endox_col) cor(endox_col, resid2))

  # Prepare result coefficients: only model coefficients (coef_x)
  result_coef <- coef_x
  names(result_coef) <- colnames(x)

  # Prepare details (diagnostics and intermediate results)
  details <- list(
    endox = endox,
    endoxstar = endoxstar,
    w = if(nw > 0) w else NULL,
    wstar = if(nw > 0) wstar else NULL,
    stage1_resid = stage1_resid,
    resid2 = resid2,
    corr_endostar_resid = corr_endostar_resid,
    sdError = sd(resid2)
  )

  # Assemble object using dedicated constructor
  result <- new_rendo_tscope(
    call = cl,
    F.formula = F.formula,
    mf = mf,
    coefficients = result_coef,
    names.main.coefs = colnames(x),
    fitted.values = fitted.values,
    residuals = resid2,
    tscope_model = res,
    details = details
  )
  
  return(result)
} 