# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

copulaCorrection_LL_rcpp <- function(params, vec_y, m_data_exo_endo, vec_data_endo_pstar, param_pos_data, param_pos_sigma, param_pos_rho) {
    .Call(`_REndo_copulaCorrection_LL_rcpp`, params, vec_y, m_data_exo_endo, vec_data_endo_pstar, param_pos_data, param_pos_sigma, param_pos_rho)
}

