name: coverage
on:
  # also whenever pulled (ie pushed) to master and dev in order to get batches
  push:
    branches:
      - development
      - master
  # default to types [opened, synchronize, reopened]
  pull_request:


jobs:
  coverage-ubuntu-latest:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: release

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: covr

      - name: Test coverage and upload to codecov.io
        run: |
          # run coverage, show, and then (try) upload
          covr_res <- covr::package_coverage()
          print(covr_res)
          # upload to codecov.io (for badge)
          covr::codecov(coverage=covr_res)
        shell: Rscript {0}
