name: coverage
on:
  # also whenever pulled (ie pushed) to master and dev in order to get batches
  push:
    branches:
      - development
      - master
  # default to types [opened, synchronize, reopened]
  pull_request:



jobs:
  coverage-ubuntu-22-04-R-release:
    runs-on: ubuntu-22.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      # to install binaries on ubuntu
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages(c('remotes'))"
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements(os="ubuntu", os_release="22.04"))')


      - name: Install package dependencies
        run: |
          remotes::install_deps(dependencies = TRUE) # installs binaries
          # testthat and covr are part of package's Suggests and installed as package dependency.
        shell: Rscript {0}

      - name: Test coverage and upload to codecov.io
        run: covr::codecov()
        shell: Rscript {0}
